// Generated by scripts/generate-error-contract.mjs. Do not edit directly.
#[derive(Debug, Clone, Copy, Serialize, PartialEq, Eq)]
pub enum ErrorCode {
    #[serde(rename = "selected_video_unavailable")]
    SelectedVideoUnavailable,
    #[serde(rename = "media_process_start_failed")]
    MediaProcessStartFailed,
    #[serde(rename = "media_process_failed")]
    MediaProcessFailed,
    #[serde(rename = "invalid_media_information")]
    InvalidMediaInformation,
    #[serde(rename = "video_stream_missing")]
    VideoStreamMissing,
    #[serde(rename = "video_width_missing")]
    VideoWidthMissing,
    #[serde(rename = "video_height_missing")]
    VideoHeightMissing,
    #[serde(rename = "video_duration_missing")]
    VideoDurationMissing,
    #[serde(rename = "video_frame_count_missing")]
    VideoFrameCountMissing,
    #[serde(rename = "video_frame_rate_missing")]
    VideoFrameRateMissing,
    #[serde(rename = "preview_cache_unavailable")]
    PreviewCacheUnavailable,
    #[serde(rename = "preview_authorization_failed")]
    PreviewAuthorizationFailed,
    #[serde(rename = "selected_path_unavailable")]
    SelectedPathUnavailable,
    #[serde(rename = "selected_path_unsupported")]
    SelectedPathUnsupported,
    #[serde(rename = "folder_read_failed")]
    FolderReadFailed,
    #[serde(rename = "folder_contains_no_supported_videos")]
    FolderContainsNoSupportedVideos,
    #[serde(rename = "directory_watch_failed")]
    DirectoryWatchFailed,
    #[serde(rename = "export_process_prepare_failed")]
    ExportProcessPrepareFailed,
    #[serde(rename = "export_process_start_failed")]
    ExportProcessStartFailed,
    #[serde(rename = "export_state_update_failed")]
    ExportStateUpdateFailed,
    #[serde(rename = "export_cancelled")]
    ExportCancelled,
    #[serde(rename = "export_process_failed")]
    ExportProcessFailed,
    #[serde(rename = "export_state_read_failed")]
    ExportStateReadFailed,
    #[serde(rename = "cancellation_state_update_failed")]
    CancellationStateUpdateFailed,
    #[serde(rename = "export_process_stop_failed")]
    ExportProcessStopFailed,
    #[serde(rename = "crop_too_small")]
    CropTooSmall,
    #[serde(rename = "crop_even_values_required")]
    CropEvenValuesRequired,
    #[serde(rename = "crop_invalid")]
    CropInvalid,
    #[serde(rename = "crop_outside_video")]
    CropOutsideVideo,
    #[serde(rename = "trim_outside_video")]
    TrimOutsideVideo,
    #[serde(rename = "metadata_trim_unsupported")]
    MetadataTrimUnsupported,
    #[serde(rename = "metadata_codec_unsupported")]
    MetadataCodecUnsupported,
    #[serde(rename = "crf_out_of_range")]
    CrfOutOfRange,
    #[serde(rename = "audio_bitrate_out_of_range")]
    AudioBitrateOutOfRange,
    #[serde(rename = "frame_rate_out_of_range")]
    FrameRateOutOfRange,
    #[serde(rename = "compatible_audio_unsupported")]
    CompatibleAudioUnsupported,
    #[serde(rename = "destination_must_be_absolute")]
    DestinationMustBeAbsolute,
    #[serde(rename = "destination_folder_unavailable")]
    DestinationFolderUnavailable,
    #[serde(rename = "destination_folder_missing")]
    DestinationFolderMissing,
    #[serde(rename = "destination_file_name_missing")]
    DestinationFileNameMissing,
    #[serde(rename = "destination_file_inspection_failed")]
    DestinationFileInspectionFailed,
    #[serde(rename = "source_replacement_requires_save")]
    SourceReplacementRequiresSave,
    #[serde(rename = "destination_already_exists")]
    DestinationAlreadyExists,
    #[serde(rename = "save_destination_mismatch")]
    SaveDestinationMismatch,
    #[serde(rename = "compatible_extension_required")]
    CompatibleExtensionRequired,
    #[serde(rename = "lossless_extension_required")]
    LosslessExtensionRequired,
    #[serde(rename = "metadata_extension_unsupported")]
    MetadataExtensionUnsupported,
    #[serde(rename = "destination_extension_missing")]
    DestinationExtensionMissing,
    #[serde(rename = "commit_output_failed")]
    CommitOutputFailed,
    #[serde(rename = "explorer_open_failed")]
    ExplorerOpenFailed,
    #[serde(rename = "explorer_unsupported")]
    ExplorerUnsupported,
    #[serde(rename = "accent_color_unavailable")]
    AccentColorUnavailable,
    #[serde(rename = "explorer_integration_update_failed")]
    ExplorerIntegrationUpdateFailed,
    #[serde(rename = "explorer_integration_unsupported")]
    ExplorerIntegrationUnsupported,
}
